#!/usr/bin/env node
// THE AVATAR'S OWN COLOUR, BAKED AT BUILD TIME -> src/app/09-avatar-tint.js
//
// The rival item in the bowl (the owner's word 2026-09-10: «саму сферу стоит заливать цветом
// аватарки») needs one tone per avatar. It is computed HERE and not in the game on purpose:
// reading a PNG back through a canvas taints it on file:// and needs the file to be there at
// all — on the portal package the avatars are not shipped. A baked table costs 49 numbers and
// cannot fail at runtime.
//
// ⚠️ THE TONE IS THE MODAL OPAQUE COLOUR, NOT THE AVERAGE: an average of fur + a white muzzle +
// a black outline is mud. Near-white and near-black are dropped for the same reason — they are
// the highlight and the outline of every avatar, not its colour.
//
// Run: node tools/avatar-tint.js     (it rewrites the module wholesale, like every generator here)
const fs = require('fs'), zlib = require('zlib'), path = require('path');
const ROOT = path.join(__dirname, '..');
const DIR = path.join(ROOT, 'avatars'), OUT = path.join(ROOT, 'src/app/09-avatar-tint.js');

function decode(file){                       // 8-bit RGBA/RGB PNG -> {w, h, px}
  const b = fs.readFileSync(file);
  if (b.readUInt32BE(0) !== 0x89504e47) throw new Error(file + ': not a png');
  let p = 8, w = 0, h = 0, ct = 0, bd = 0, idat = [], plte = null, trns = null;
  while (p < b.length){
    const len = b.readUInt32BE(p), type = b.toString('ascii', p + 4, p + 8);
    if (type === 'IHDR'){ w = b.readUInt32BE(p + 8); h = b.readUInt32BE(p + 12);
      bd = b[p + 16]; ct = b[p + 17]; }
    else if (type === 'PLTE') plte = b.slice(p + 8, p + 8 + len);
    else if (type === 'tRNS') trns = b.slice(p + 8, p + 8 + len);
    else if (type === 'IDAT') idat.push(b.slice(p + 8, p + 8 + len));
    else if (type === 'IEND') break;
    p += 12 + len;
  }
  if (bd !== 8 || (ct !== 6 && ct !== 2 && ct !== 3))
    throw new Error(file + ': need 8-bit RGB(A) or palette, got ' + bd + '/' + ct);
  const ch = ct === 6 ? 4 : (ct === 2 ? 3 : 1);
  const raw = zlib.inflateSync(Buffer.concat(idat)), stride = w * ch;
  const px = Buffer.alloc(h * stride);
  for (let y = 0; y < h; y++){                                    // unfilter, per the spec
    const f = raw[y * (stride + 1)], line = raw.slice(y * (stride + 1) + 1, (y + 1) * (stride + 1));
    for (let x = 0; x < stride; x++){
      const a = x >= ch ? px[y * stride + x - ch] : 0;
      const bb = y > 0 ? px[(y - 1) * stride + x] : 0;
      const c = (x >= ch && y > 0) ? px[(y - 1) * stride + x - ch] : 0;
      let v = line[x];
      if (f === 1) v += a; else if (f === 2) v += bb; else if (f === 3) v += (a + bb) >> 1;
      else if (f === 4){ const pa = Math.abs(bb - c), pb = Math.abs(a - c), pc = Math.abs(a + bb - 2 * c);
        v += (pa <= pb && pa <= pc) ? a : (pb <= pc ? bb : c); }
      px[y * stride + x] = v & 255;
    }
  }
  if (ct !== 3) return { w, h, ch, px };
  const out = Buffer.alloc(w * h * 4);                            // expand the palette to RGBA
  for (let i = 0; i < w * h; i++){
    const idx = px[i];
    out[i * 4] = plte[idx * 3]; out[i * 4 + 1] = plte[idx * 3 + 1]; out[i * 4 + 2] = plte[idx * 3 + 2];
    out[i * 4 + 3] = (trns && idx < trns.length) ? trns[idx] : 255;
  }
  return { w, h, ch: 4, px: out };
}

function tint(file){
  const { w, h, ch, px } = decode(file), bins = new Map();
  for (let i = 0; i < w * h; i++){
    const o = i * ch, a = ch === 4 ? px[o + 3] : 255;
    if (a < 200) continue;
    const r = px[o], g = px[o + 1], b = px[o + 2];
    const mx = Math.max(r, g, b), mn = Math.min(r, g, b);
    if (mx > 244 && mn > 232) continue;                            // the white of a muzzle or an eye
    if (mx < 64) continue;                                         // the outline and the pupils
    const k = ((r >> 4) << 8) | ((g >> 4) << 4) | (b >> 4);        // quantised to 16 levels
    const e = bins.get(k) || [0, 0, 0, 0];
    e[0] += r; e[1] += g; e[2] += b; e[3]++; bins.set(k, e);
  }
  let best = null;
  for (const e of bins.values()) if (!best || e[3] > best[3]) best = e;
  if (!best) return 0xc0c4cc;                                      // an avatar with no opaque body
  const n = best[3];
  return ((Math.round(best[0] / n) << 16) | (Math.round(best[1] / n) << 8) | Math.round(best[2] / n));
}

const files = fs.readdirSync(DIR).filter(f => /^Avatar\d+\.png$/.test(f))
  .sort((a, b) => parseInt(a.slice(6), 10) - parseInt(b.slice(6), 10));
const list = files.map(f => tint(path.join(DIR, f)));
const rows = [];
for (let i = 0; i < list.length; i += 7)
  rows.push('  ' + list.slice(i, i + 7).map(v => '0x' + v.toString(16).padStart(6, '0')).join(', '));
fs.writeFileSync(OUT, `// GENERATED by tools/avatar-tint.js — DO NOT EDIT BY HAND.
// One tone per avatar file: the MODAL opaque colour of avatars/AvatarNN.png (index 0 = Avatar01).
// It paints the body of the rival item in the bowl, so the piece reads as that player's colour
// before its face is even legible. Re-run the tool when the owner's avatars change.
// ⚠️ THE NUMBERS ARE sRGB: a material colour is LINEAR in three, so a consumer converts.
const AVATAR_TINT = [
${rows.join(',\n')},
];
// the tone of avatar number n (1-based, as the files are named); an unknown number -> a neutral
function avatarTint(n){
  const i = (n | 0) - 1;
  return (i >= 0 && i < AVATAR_TINT.length) ? AVATAR_TINT[i] : 0xc0c4cc;
}
`);
console.log('wrote ' + OUT + ' (' + list.length + ' avatars)');
console.log(list.slice(0, 6).map((v, i) => 'Avatar0' + (i + 1) + ' #' + v.toString(16).padStart(6, '0')).join('  '));
