#!/usr/bin/env python3
# ===== tools/hitfx-pack.py — repack flashyfeather hit animations into src/app/37-hitfx.js =====
# The owner 2026-08-30: «khochu effekty 4, 13, 14, 16, 17 i kachestvo spraytov nuzhno podnyat»
# (flashyfeather.itch.io/hit-animations-vol2, downloaded into «Hits2 Animations/»).
#
#   python3 tools/hitfx-pack.py 4 13 14 16 17          # the live set
#   python3 tools/hitfx-pack.py 11 --size 256          # try another effect / another quality
#
# ⛔ THE SOURCE PACK IS GITIGNORED: the licence covers use in a game, not redistribution of the
# assets. The game embeds only this repacked subset. The file is FULLY REGENERATED every run.
#
# ⚠️⚠️ THE THREE NUMBERS AND WHY THEY ARE WHAT THEY ARE (measured 2026-08-30, all five effects):
#  SIZE 192 (source cells are 512). Cropping buys nothing — the ink fills 92-100% of the cell,
#    measured. On screen the flash is ~240 device px on a DPR-2 phone, so 128 was genuinely
#    under-resolved (the owner saw it). 192 is the balance point:
#      size | base64 (5 effects) |  VRAM (RGBA, all five resident)
#      128  |  362 KB            |   7.5 MB
#      192  |  633 KB            |  16.9 MB   <- shipped
#      256  |  943 KB            |  30.0 MB
#    VRAM is the binding constraint, not download: the game's model atlases are 11 MB total, so
#    256 would nearly quadruple the texture budget on the very phones that reported lag.
#  FRAMES 24 of the source's 60, played at 40 fps = 0.6 s. 30 frames costs +25% of both numbers
#    for 50 fps — imperceptible on a 0.6 s flash.
#  WEBP q80, and it is the FIRST WebP in this project (33 PNG data URIs precede it). Justified:
#    PNG at this size is 1020 KB against 633. Any browser that runs our Rapier WASM and WebGL
#    supports WebP with alpha — the only gap is Safari 13 (2019). ⚠️ AND THE FAILURE IS SAFE BY
#    CONSTRUCTION: the texture starts blank and is filled on img.onload, so a browser that
#    cannot decode it simply shows NO flash. Nothing throws, nothing else changes.
import io, sys, base64, math
from PIL import Image

SRC = 'Hits2 Animations/%s.png'
OUT = 'src/app/37-hitfx.js'
args = [a for a in sys.argv[1:] if not a.startswith('--')]
opts = {a.split('=')[0]: a.split('=')[1] for a in sys.argv[1:] if a.startswith('--') and '=' in a}
EFFECTS = args or ['4', '13', '14', '16', '17']
SIZE = int(opts.get('--size', 192))
TAKE = int(opts.get('--frames', 24))
FPS  = int(opts.get('--fps', 40))
COLS = 6

def pack(num):
    im = Image.open(SRC % num)
    g = 8; cell = im.size[0] // g
    a = im.split()[3]
    occ = [(r, c) for r in range(g) for c in range(g)
           if a.crop((c*cell, r*cell, (c+1)*cell, (r+1)*cell)).getbbox()]
    idxs = [occ[min(len(occ)-1, round(i*(len(occ)-1)/(TAKE-1)))] for i in range(TAKE)]
    rows = math.ceil(TAKE / COLS)
    sheet = Image.new('RGBA', (COLS*SIZE, rows*SIZE), (0, 0, 0, 0))
    for k, (r, c) in enumerate(idxs):
        fr = im.crop((c*cell, r*cell, (c+1)*cell, (r+1)*cell)).resize((SIZE, SIZE), Image.LANCZOS)
        sheet.paste(fr, ((k % COLS)*SIZE, (k // COLS)*SIZE))
    buf = io.BytesIO()
    sheet.save(buf, 'WEBP', quality=80, method=6)
    return rows, base64.b64encode(buf.getvalue()).decode(), len(occ)

entries, total = [], 0
for num in EFFECTS:
    rows, b64, src_n = pack(num)
    total += len(b64)
    entries.append("  { id:%s, cols:%d, rows:%d, n:%d, fps:%d,\n    png:'data:image/webp;base64,%s' }"
                   % (num, COLS, rows, TAKE, FPS, b64))
    print('  effect %-3s %2d source frames -> %d @ %dpx  (%d KB)' % (num, src_n, TAKE, SIZE, len(b64)//1024))

js = """// ===== 37-hitfx: the match-hit flashes (flashyfeather hit-animations-vol2) =====
// Generated by tools/hitfx-pack.py — DO NOT HAND-EDIT, rerun the tool. The owner's set of
// 2026-08-30: effects %s at %d px, %d frames each, %d fps (~%.2f s per hit).
// ⚠️ The consumer is spawnHitFx (70-fx): it picks one of these AT RANDOM per match, so the
// effect does not become wallpaper. Textures are built LAZILY, one per effect on first use.
// ⚠️ WebP with alpha, deliberately — see the tool's header for the measured reasoning and for
// the graceful failure (a browser that cannot decode it shows no flash and nothing else).
const HITFX_SET = [
%s
];
const _hitFxTex = {};
function hitFxTexture(i){
  if (_hitFxTex[i]) return _hitFxTex[i];
  const img = new Image();
  const tex = new THREE.Texture(img);
  img.onload = () => { tex.needsUpdate = true; };
  img.src = HITFX_SET[i].png;
  tex.minFilter = THREE.LinearFilter; tex.magFilter = THREE.LinearFilter;
  tex.generateMipmaps = false;
  _hitFxTex[i] = tex;
  return tex;
}
""" % (', '.join(EFFECTS), SIZE, TAKE, FPS, TAKE/FPS, ',\n'.join(entries))
io.open(OUT, 'w', encoding='utf-8').write(js)
print('%d effects, %d KB embedded, VRAM if all resident: %.1f MB'
      % (len(EFFECTS), total//1024, len(EFFECTS)*COLS*SIZE*math.ceil(TAKE/COLS)*SIZE*4/1048576))
