// Skyboxes -> data module src/app/05-sky.js (single-file build, no loaders).
//
// The sources are 4096x2048 PNGs at ~1 MB each — you can't put that into the build.
// The sky is smooth, so JPEG compresses it tens of times over with no visible loss:
// measurement 1536x768 q0.78 -> 36 KB base64 against 1027 KB PNG.
//
// ⚠️ Number 05: the module must come BEFORE 10-stage, which builds the sky
// (build.py concatenates src/app/*.js alphabetically, and this is a top-level const).
//
// Run: node tools/sky2module.js "3d assets/skyboxes/Skyboxes" src/app/05-sky.js
const { chromium } = require('playwright');
const fs = require('fs'), path = require('path');

const W = 1536, Q = 0.78;
// Three times of day. alien/space are deliberately NOT taken — that is novelty, not background.
const WANT = [['morning', 'skybox-morning.png'], ['day', 'skybox-day.png'], ['night', 'skybox-night.png']];

(async () => {
  const [srcDir, outPath] = process.argv.slice(2);
  // without the check the next session would silently build garbage: node does not complain
  // about undefined in path.join, and fs.existsSync returns false for every panorama
  if (!srcDir || !outPath) {
    console.error('Run: node tools/sky2module.js <skybox directory> <out.js>');
    console.error('Example: node tools/sky2module.js "3d assets/skyboxes/Skyboxes" src/app/05-sky.js');
    process.exit(1);
  }
  if (!fs.existsSync(srcDir)) {
    console.error('Directory not found:', srcDir);
    process.exit(1);
  }
  const b = await chromium.launch();
  const p = await b.newPage();
  const parts = [`// ===== 05-sky: sky panoramas (data module) =====
// Generated by tools/sky2module.js — DO NOT EDIT BY HAND.
// Equirectangular panoramas ${W}x${W / 2}, JPEG.
// The 4096x2048 PNG originals at ~1 MB each live in "3d assets/skyboxes".`];
  const names = [];
  for (const [key, file] of WANT) {
    const f = path.join(srcDir, file);
    if (!fs.existsSync(f)) { console.log('⚠ FILE MISSING', file); continue; }
    const b64 = fs.readFileSync(f).toString('base64');
    const uri = await p.evaluate(async ([b64, w, q]) => {
      const img = new Image(); img.src = 'data:image/png;base64,' + b64; await img.decode();
      const c = document.createElement('canvas'); c.width = w; c.height = w / 2;
      c.getContext('2d').drawImage(img, 0, 0, w, w / 2);
      return c.toDataURL('image/jpeg', q);
    }, [b64, W, Q]);
    parts.push(`const SKY_${key.toUpperCase()} = '${uri}';`);
    names.push([key, uri.length]);
    console.log(`  ${file.padEnd(22)} -> ${key.padEnd(8)} ${Math.round(uri.length / 1024)} KB`);
  }
  parts.push(`// Selection by the CLOCK ON THE PLAYER'S MACHINE (the owner's spec 2026-07-21).
// Boundaries: morning 5-11, day 11-18, night 18-5. Being wrong here is not scary —
// this is background, not gameplay, so we do no time synchronization at all.
function skyForNow(){
  let h = 12;
  try { h = new Date().getHours(); } catch(e){}
  if (h >= 5 && h < 11) return SKY_MORNING;
  if (h >= 11 && h < 18) return SKY_DAY;
  return SKY_NIGHT;
}`);
  fs.writeFileSync(outPath, parts.join('\n') + '\n');
  console.log(`${outPath}: ${Math.round(fs.statSync(outPath).size / 1024)} KB, panoramas ${names.length}`);
  await b.close();
})();
